name: Unit Tests with Jest
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing npm 
        working-directory: ./frontend
        run: npm install 
      - name: Running Jest unit tests
        working-directory: ./frontend
        run:  npm test